[project]
name = "pdf-extraction-agenda"
version = "0.1.0"
description = "Overview of pipelines related to PDF document processing"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.0,<3",
    "py-markdown-table>=1.3.0",
]
